### ISSUE TITLE
A Python implementation on pypi

### ISSUE THREAD

**Issue by sauln** [CSU-TDA/PersistenceImages#3]
Hey Henry,  

I wanted to let you and the community at large know that I put together a persistence images implementation in Python a little while ago.  Others might find it useful if they are unable to use matlab, or don't want to set up and implementation themselves.

It's installable via pip 
```
pip install persim
``` 
and can be found at [sauln/persim](https://github.com/sauln/persim).

**Comment by henryadams** [comment]
Hi Saul,

Very cool! I added a link to your python implementation, as well as to another python implementation that I also just learned about today, to the README.md file for this github project. Indeed, in our readme, we now write:

"Two different implementations of persistence images (both in python instead of Matlab) are available at https://gitlab.com/csu-tda/PersistenceImages and at https://github.com/sauln/persim."

Best, Henry
